### ISSUE TITLE
live_compute_example_app.py error

### ISSUE THREAD

**Issue by timothydmorton** [wen-jams/bsavi#105]
Just tried to run `panel serve app/live_compute_example_app.py` and get this:
```
2023-11-21 16:32:14,567 Starting Bokeh server with process id: 22665
2023-11-21 16:32:32,526 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x12d6d8f10>: Observable.__init__() got an unexpected keyword argument 'myfunc'
File 'live_compute_example_app.py', line 52, in <module>:
waveforms = bsv.Observable( Traceback (most recent call last):
  File "/Users/tmorton/miniconda3/envs/inviz/lib/python3.11/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "/Users/tmorton/personal/repositories/inviz/app/live_compute_example_app.py", line 52, in <module>
    waveforms = bsv.Observable(
                ^^^^^^^^^^^^^^^
TypeError: Observable.__init__() got an unexpected keyword argument 'myfunc'
```

**Comment by wen-jams** [comment]
app should work now, assuming you're running the latest alpha release from pip (0.4.0a0) or cloning main branch. fixed with #107
